Added Navbar component
m3ntorship/personal-resume pull request #23
Opened 2020-09-15 23:19 UTC by eslamheshamm

2020-09-15 23:25 UTC, Nilegfx requested changes

2020-09-15 23:25 UTC, Nilegfx commented on frontend/src/components/Navbar/Navbar.jsx
> +  return (
create static data array and loop through it instead of copying and pasting multiple times.

2020-09-15 23:25 UTC, Nilegfx commented on frontend/src/components/Navbar/Navbar.jsx
> +export default Navbar;
you can save this line and directly export the lonely class in this file.

2020-09-16 12:32 UTC, MAlngaawy approved these changes
LGTM

2020-09-16 18:59 UTC, Nilegfx commented on frontend/src/components/Navbar/Navbar.jsx
> +    API('/navigation').then(({ data: navigation }) => {
Please handle the failure case `.catch(()=>{})

2020-09-16 19:03 UTC, Nilegfx commented on frontend/src/components/Navbar/Navbar.jsx
> +              key={index}
please use different key than the index when it is possible, why?[read more](https://medium.com/@vraa/why-using-an-index-as-key-in-react-is-probably-a-bad-idea-7543de68b17c)

2020-09-16 19:06 UTC, Nilegfx commented on frontend/src/components/Navbar/Navbar.jsx
> +        {links.map((link, index) => {
please destructure the data you need at this step

2020-09-16 19:09 UTC, Nilegfx commented on frontend/src/components/Navbar/Navbar.jsx
> +              href="/"
please add `href` and other needed properties to the data model

2020-09-16 19:10 UTC, Nilegfx requested changes, later dismissed
please check my changes request.

2020-09-18 23:20 UTC, merged