completed initial style for responsive navbar
m3ntorship/personal-resume pull request #67
Opened 2020-09-21 01:08 UTC by seifeldeen3388

2020-09-21 12:18 UTC, Tramsi commented on frontend/src/components/Navbar/index.jsx
> +    document.getElementById('mobileNav').classList.toggle('hidden');
It's not a good practice to use getElementById .. Avoid manipulating DOM directly 
React have all the tools you need to achieve the same result and logic

2020-09-21 20:25 UTC, MAlngaawy requested changes
please consider these changes
- paragraph & heading width
- the image size
- the buttons width and height
- navbar box-shadow instead of padding

2020-09-22 10:23 UTC, MAlngaawy approved these changes
Very Nice Work Saif
LGTM

2020-09-22 10:38 UTC, Nilegfx commented
looking forward to merge this PR 😍

2020-09-22 11:19 UTC, merged